### ISSUE TITLE
[Landing page] AACRGPTDev, when I update the webapp. A feature branch is deployed to aws.

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#149]
Description:
Need to set up CI for this. 

Plan is: dev account with personal stages -> on PR, create feat stage for tests
staging: preview stage for QA -> merge main
prod: prod deployment. -> manual release

Validation:
We have a CI which deploys a feat stack

Tech steps:
define a naming structure for our branches eg. feat/mc/149-ci-update-webapp

modify the pr.yml to get the stage name of the branch. if the branch is dev, staging or prod don't run. Otherwise build a stage name which is like feat-149-ci-update-webapp and deploy the webapp to the dev environment.

on merge make sure that the stack/stage is deleted. 
create a new workflow. delete-stage.yml 
this should run on merge to main
it should extract the stagename again and run destroy.

**Comment by mattzcarey** [comment]
```yml
  get-env-name:
    name: 🌎 Determine AWS environment
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      env_name: ${{ steps.get-env-name.outputs.env_name }}
      stage_name: ${{ steps.build-stage-name.outputs.stage_name }}
    steps:
      - name: 📦 Get environment name
        id: get-env-name
        run: |
          case ${{ env.BASE_BRANCH }} in
            main) echo "::set-output name=env_name::DEV" ;;
            staging) echo "::set-output name=env_name::STAGING" ;;
            prod) echo "::set-output name=env_name::PROD" ;;
            *) echo "Unknown branch name: ${{ env.BASE_BRANCH }}" && exit 1 ;;
          esac
      - name: 🎭 Build stage name
        id: build-stage-name
        run: |
          stage_name=$(echo "${{ env.SOURCE_BRANCH }}" | sed -E 's/^([^-]+-[^-]+).*/\1/' | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=stage_name::$stage_name"
```
