### ISSUE TITLE
[BUG] Cannot find module @gitbeaker/rest error occurs during Run code review script step in github workflow

### ISSUE THREAD

**Issue by CirillaQL** [mattzcarey/code-review-gpt#323]
### Current Behavior:

![error](https://github.com/mattzcarey/code-review-gpt/assets/46399960/e50bd76d-13a9-4cde-9eed-55959d87e5a0)

### Expected Behavior:

Run without error

### Steps To Reproduce:

I try two kinds of workflow yml:
![workflow_1](https://github.com/mattzcarey/code-review-gpt/assets/46399960/87fbe314-3f99-4356-9f89-fab09f06dfb8)
![workflow_2](https://github.com/mattzcarey/code-review-gpt/assets/46399960/73480669-81b4-45ed-b6f0-556e28602420)
but both of them return same @gitbeaker/rest error

### Environment:

github workflow

### Anything else:

Hi, this CI yml from my own test project: https://github.com/CirillaQL/networkCheck . I set openai_key_value only in Settings->Actions->Repository secrets. Don't know how to fix it, may be @gitbeaker/rest new version problem?

**Comment by mattzcarey** [comment]
Hi, thanks for your issue. There is an issue with eslint resolving exports in package.json. This causes an issue with the @gitbeaker/rest package. https://github.com/jdalrymple/gitbeaker/issues/3230

I managed to replicate locally using pnpm to install but not with npm. And I am unable to replicate it in a github runner. Please can you try running the package locally with `npm i code-review-gpt && npx code-review-gpt review`

**Comment by CirillaQL** [comment]
> Hi, thanks for your issue. There is an issue with eslint resolving exports in package.json. This causes an issue with the @gitbeaker/rest package. [jdalrymple/gitbeaker#3230](https://github.com/jdalrymple/gitbeaker/issues/3230)
> 
> I managed to replicate locally using pnpm to install but not with npm. And I am unable to replicate it in a github runner. Please can you try running the package locally with `npm i code-review-gpt && npx code-review-gpt review`

Hi, sorry for this late response.  I tried to run the package locally with `npm i code-review-gpt && npx code-review-gpt review --ci=github --remote=CirillaQL/networkCheck#1` and it looks fine to me. I love this project and manage to introduce it to my CICD co-workers. Really hope can fix it in github runner. Should I keep this issue open?

**Comment by kakshaycs** [comment]
I am using something  similar 
```
name: Review GPT

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Code Review GPT
        run: npm install code-review-gpt
      
      - name: Run Code Review GPT
        run: npx code-review-gpt review --ci=github --model=$MODEL
        
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          MODEL: 'gpt-3.5-turbo'
          OPENAI_API_KEY: ${{ secrets.MY_SECRET_CODE }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          
   ```
   The workflow ran successfully, but there was no output.
