### ISSUE TITLE
Suggestion: Docs should suggest adding bot reviewer

### ISSUE THREAD

**Issue by scosman** [mattzcarey/code-review-gpt#337]
The current docs suggest an `on: pull_request` trigger. However, costs can add up. GPT4 isn't cheap, and many small pushes to a PR will run it many many times. Potentially including before the PR is ready for review.

I suggest updating docs to run the review when a reviewer bot is added as a reviewer. See below. 

```
on:
  pull_request:
    types: [ review_requested ]

jobs:
  run_code_review:
    if: ${{ github.event.requested_reviewer.login == 'your-bot-name'}}
```
